#!/usr/bin/env bash

# scripy to start a MySQL server with a mapped local directory for data

docker rm -f mariadb-server >/dev/null 2>/dev/null
docker run -d \
        --name mariadb-server \
        -e MYSQL_ROOT_PASSWORD=rootpass \
        -e MYSQL_USER=moodle_user \
        -e MYSQL_PASSWORD=moodle \
        -e MYSQL_ROOT_HOST=172.17.0.1 \
        -p 3307:3306 \
	-v /Users/opitz/workbench/mariadb/data:/var/lib/mysql \
 mariadb:10.7

ipaddr=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" maria-server)
echo "mariadb-server running on $ipaddr"

